name: CD - Deploy to Server

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Deploy (run deploy.sh on server)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: 2222
          script: |
            bash -lc "
            echo '[CD] Stopping existing containers...'
            docker stop hyundai-wnp || true
            docker rm hyundai-wnp || true
            echo '[CD] Running deploy script...'
            /opt/hyundai-wnp/deploy.sh | tee -a /opt/hyundai-wnp/deploy.log
            "
